# .goreleaser.yml
before:
  hooks:
    # You may remove this if you don't use vgo and don't need go.mod support
    - go mod tidy

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - 386
    - arm64
  goarm:
    - '6' # For ARMv6
    - '7' # For ARMv7
  ignore:
    - goos: darwin
      goarch: 386 # darwin 386 is not supported by Go anymore
  ldflags:
    - -s -w # Strip binary for smaller size

archives:
  - id: archive
    builds:
      - main
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
